# Generated by Django 3.2.8 on 2021-10-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=128, verbose_name='사용자 이메일')),
            ],
        ),
        migrations.CreateModel(
            name='save',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberid', models.IntegerField(default=0)),
                ('webtoonid', models.TextField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='webtoon',
            fields=[
                ('id', models.IntegerField(primary_key='True', serialize=False)),
                ('week', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('URL', models.TextField(verbose_name='Site URL')),
                ('thumbnail', models.TextField(verbose_name='Site THUMB')),
                ('author', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('genre', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
            ],
        ),
    ]
